services:
  - type: worker
    name: futures-compression-accum-scanner
    env: python
    plan: starter
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "/app/start.sh"
    envVars:
      - key: 8046031500:AAGpTEu6uf6-I5fqOQ2h3SqBShZzs1bkSe8
        sync: false
      - key: 6614671189
        sync: false
      - key: 1C678RShUzqW0o26MWA6bJtgG0A98J07gxh1iWxZHOu0
        sync: false
      - key: GSHEET_TAB
        value: signals
      - key: GSHEET_CREDS_B64
        sync: false
