services:
  - type: worker
    name: futures-compression-accum-scanner
    env: python
    plan: starter
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "/app/start.sh"
    envVars:
      - key: TG_TOKEN
        sync: false
      - key: TG_CHAT
        sync: false
      - key: GSHEET_ID
        sync: false
      - key: GSHEET_TAB
        value: signals
      - key: GSHEET_CREDS_B64
        sync: false
